<?php if (get_field('facebook', 'options')){ ?><a href="<?php the_field('facebook', 'options');?>"><span class="fa fa-3x fa-facebook"></span></a><?php } ?>
<?php if (get_field('twitter', 'options')){ ?><a href="<?php the_field('twitter', 'options');?>"><span class="fa fa-3x fa-twitter"></span></a><?php } ?>
<?php if (get_field('google_plus', 'options')){ ?><a href="<?php the_field('google_plus', 'options');?>"><span class="fa fa-3x fa-google-plus"></span></a><?php } ?>
<?php if (get_field('linkedin', 'options')){ ?><a href="<?php the_field('linkedin', 'options');?>"><span class="fa fa-3x fa-linkedin"></span></a><?php } ?>
<?php if (get_field('instagram', 'options')){ ?><a href="<?php the_field('instagram', 'options');?>"><span class="fa fa-3x fa-instagram"></span></a><?php } ?>
<?php if (get_field('flickr', 'options')){ ?><a href="<?php the_field('flickr', 'options');?>"><span class="fa fa-3x fa-flickr"></span></a><?php } ?>
<?php if (get_field('youtube', 'options')){ ?><a href="<?php the_field('youtube', 'options');?>"><span class="fa fa-3x fa-youtube"></span></a><?php } ?>
<?php if (get_field('tumblr', 'options')){ ?><a href="<?php the_field('tumblr', 'options');?>"><span class="fa fa-3x fa-tumblr"></span></a><?php } ?>
<?php if (get_field('pinterest', 'options')){ ?><a href="<?php the_field('pinterest', 'options');?>"><span class="fa fa-3x fa-pinterest"></span></a><?php } ?>